Fix unicode encode error when generating slugs (#5)
When baking College Physics on qa.cnx.org:

```
Traceback (most recent call last):
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/tasks.py", line 31, in __call__
    return super(PyramidAwareTask, self).__call__(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/db.py", line 74, in wrapped
    return func(*args, **kwargs)
  File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/subscribers.py", line 167, in baking_processor
    bake(binder, recipe_id, publisher, message, cursor=cursor)
  File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/db.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/bake.py", line 92, in bake
    amend_tree_with_slugs(tree)
  File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/utils.py", line 70, in amend_tree_with_slugs
    amend_tree_with_slugs(node, title_seq)
  File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/utils.py", line 70, in amend_tree_with_slugs
    amend_tree_with_slugs(node, title_seq)
  File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/utils.py", line 67, in amend_tree_with_slugs
    tree['slug'] = generate_slug(*title_seq)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxcommon/urlslug.py", line 47, in generate_slug
    result = '{}-{}'.format(number, result)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 32: ordinal not in range(128)
```

This is because College Physics contains unicode apostrophes in some of
its chapters and sections.